/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author t1
 */
public class kozoskepviselo extends javax.swing.JDialog {

    private DbConnection dbConnection = null;

    /**
     * Creates new form Sugo
     */
    public kozoskepviselo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        dbConnection = DbConnection.getInstance();
        Show_UsersList_In_JTable();
    }

    public void Show_UsersList_In_JTable() {

        ArrayList<DbConnection.Users> list = dbConnection.getkezelo();
        DefaultTableModel model = (DefaultTableModel) Listatabla.getModel();

        model.setRowCount(0);
        Object[] row = new Object[2];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).ID();
            row[1] = list.get(i).Nev();

            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBkepvieslo = new javax.swing.JButton();
        JTnev = new javax.swing.JTextField();
        kozoskeptorol = new javax.swing.JButton();
        JModosit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Listatabla = new javax.swing.JTable();
        JBFrissit = new javax.swing.JButton();
        Jtorol1 = new javax.swing.JTextField();
        JTID = new javax.swing.JTextField();
        JLID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Közösképviselő hozzáadása");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        JBkepvieslo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBkepvieslo.setMnemonic('k');
        JBkepvieslo.setText("Közösképviselő hozzáadása");
        JBkepvieslo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBkepviesloActionPerformed(evt);
            }
        });

        kozoskeptorol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kozoskeptorol.setMnemonic('k');
        kozoskeptorol.setText("Közösképviselő törlése");
        kozoskeptorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kozoskeptorolActionPerformed(evt);
            }
        });

        JModosit.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        Listatabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Név"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Listatabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListatablaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListatablaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Listatabla);
        if (Listatabla.getColumnModel().getColumnCount() > 0) {
            Listatabla.getColumnModel().getColumn(0).setResizable(false);
            Listatabla.getColumnModel().getColumn(1).setResizable(false);
        }

        JBFrissit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBFrissit.setText("Módosít");
        JBFrissit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFrissitActionPerformed(evt);
            }
        });

        Jtorol1.setEditable(false);
        Jtorol1.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        JTID.setEditable(false);
        JTID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        JLID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JLID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLID.setText("Közösképviselő ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JBkepvieslo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kozoskeptorol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JBFrissit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTnev, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JModosit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jtorol1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLID, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLID)
                    .addComponent(JTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTnev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBkepvieslo))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jtorol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(kozoskeptorol)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBFrissit)
                    .addComponent(JModosit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBkepviesloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBkepviesloActionPerformed
//közösképviselő hozzáadása után tisztitjuk a táblákat
        if (JTnev.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Kérem Adjon meg egy Nevet", "Üres Mező", JOptionPane.INFORMATION_MESSAGE);

        } else {
            dbConnection.uj(JTnev.getText());
            JTnev.setText("");
        }  //Meghivjuk a Tábla methodust hogy lásuk mi van benne
        Show_UsersList_In_JTable();
    }//GEN-LAST:event_JBkepviesloActionPerformed

    private void kozoskeptorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kozoskeptorolActionPerformed
        //Törlés után nullázuk az összes beviteli mezőt
        if (Jtorol1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "KéremVálaszon Nevet", "Üres Mező", JOptionPane.INFORMATION_MESSAGE);
        } else {
            dbConnection.kepviselotorol(JModosit.getText());
            //Show_UsersList_In_JTable();
            Jtorol1.setText("");
            JModosit.setText("");
            JTID.setText("");
        }  //Meghivjuk a Tábla methodust hogy lásuk mi van benne
        Show_UsersList_In_JTable();
    }//GEN-LAST:event_kozoskeptorolActionPerformed

    private void ListatablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListatablaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ListatablaMouseEntered

    private void ListatablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListatablaMouseClicked
        int i = Listatabla.getSelectedRow();
        TableModel model = Listatabla.getModel();
        JTID.setText(model.getValueAt(i, 0).toString());
        JModosit.setText(model.getValueAt(i, 1).toString());
        Jtorol1.setText(model.getValueAt(i, 1).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_ListatablaMouseClicked

    private void JBFrissitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFrissitActionPerformed
        //Frissités után nullázuk az összes beviteli mező értékét
        if (JModosit.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "KéremVálaszon Nevet", "Üres Mező", JOptionPane.INFORMATION_MESSAGE);

        } else {
            dbConnection.keviselofriss(JModosit.getText(), JTID.getText());
            Jtorol1.setText("");
            JModosit.setText("");
            JTID.setText("");

        }
        //Meghivjuk a Tábla methodust hogy lásuk mi van benne
        Show_UsersList_In_JTable();

    }//GEN-LAST:event_JBFrissitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kozoskepviselo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kozoskepviselo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kozoskepviselo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kozoskepviselo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                kozoskepviselo dialog = new kozoskepviselo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBFrissit;
    private javax.swing.JButton JBkepvieslo;
    private javax.swing.JLabel JLID;
    private javax.swing.JTextField JModosit;
    public javax.swing.JTextField JTID;
    private javax.swing.JTextField JTnev;
    private javax.swing.JTextField Jtorol1;
    private javax.swing.JTable Listatabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kozoskeptorol;
    // End of variables declaration//GEN-END:variables
}
