
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author t1
 */
public class Lakok extends javax.swing.JDialog {

    private DbConnection dbConnection = null;
    DefaultTableModel tm;

    public Lakok(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dbConnection = DbConnection.getInstance();
        Show_UsersList_In_JTable();
        dbConnection.LakoCombobox();
    }

    public void Show_UsersList_In_JTable() {

        ArrayList<DbConnection.Users2> list = dbConnection.lako();
        DefaultTableModel model = (DefaultTableModel) lakok_table.getModel();
        Object[] row = new Object[6];
        model.setRowCount(0);
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).ID();
            row[1] = list.get(i).Nev();
            row[2] = list.get(i).Emelet();
            row[3] = list.get(i).Ajto();
            row[4] = list.get(i).Negyzetmeter();
            row[5] = list.get(i).Nev1();

            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JTnev = new javax.swing.JTextField();
        JTemelet = new javax.swing.JTextField();
        JTajto = new javax.swing.JTextField();
        JTnegyzetmeter = new javax.swing.JTextField();
        JBhozza = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lakok_table = new javax.swing.JTable();
        JBLaktorol = new javax.swing.JButton();
        JBModosit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JTID = new javax.swing.JTextField();
        Lakok_combo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Haz_ID = new javax.swing.JTextField();
        JBModosit1 = new javax.swing.JButton();

        jTextField5.setText("jTextField5");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lakók Kezelése");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Név:");
        jLabel4.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Emelet:");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ajtó:");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Lakás m2:");
        jLabel8.setToolTipText("");

        JTnev.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTnev.setMinimumSize(new java.awt.Dimension(6, 150));

        JTemelet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTemelet.setMinimumSize(new java.awt.Dimension(6, 150));

        JTajto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTajto.setMinimumSize(new java.awt.Dimension(6, 150));

        JTnegyzetmeter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTnegyzetmeter.setMinimumSize(new java.awt.Dimension(6, 150));

        JBhozza.setText("Lakó hozzáadása");
        JBhozza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBhozzaActionPerformed(evt);
            }
        });

        lakok_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Név", "Emelet", "Ajtó", "Lakás m2", "Kezelő neve"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lakok_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        lakok_table.setColumnSelectionAllowed(true);
        lakok_table.setRowHeight(30);
        lakok_table.getTableHeader().setReorderingAllowed(false);
        lakok_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lakok_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lakok_table);
        lakok_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        JBLaktorol.setText("Lakó törlése");
        JBLaktorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLaktorolActionPerformed(evt);
            }
        });

        JBModosit.setText("Módosít");
        JBModosit.setToolTipText("");
        JBModosit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModositActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID:");
        jLabel1.setToolTipText("");

        JTID.setEditable(false);
        JTID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Lakok_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lakok_comboActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ház név:");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ház ID:");
        jLabel3.setToolTipText("");

        Haz_ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        JBModosit1.setText("Reset");
        JBModosit1.setToolTipText("");
        JBModosit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModosit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Haz_ID))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTnegyzetmeter, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTajto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTnev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Lakok_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JTemelet, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(JTID))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBhozza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBLaktorol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBModosit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBModosit1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel6, jLabel7, jLabel8});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lakok_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Haz_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTnev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTemelet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JTajto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JTnegyzetmeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBhozza)
                    .addComponent(JBLaktorol)
                    .addComponent(JBModosit)
                    .addComponent(JBModosit1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBhozzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBhozzaActionPerformed

        Show_UsersList_In_JTable();
        if (JTnev.getText().equals("") || JTemelet.equals("") || JTajto.equals("") || JTnegyzetmeter.equals("")) {
            JOptionPane.showMessageDialog(null, "Kérem Vigye fel az összes adatott", "Üres Mező", JOptionPane.INFORMATION_MESSAGE);

        } else {
            dbConnection.ujlako(JTnev.getText(), Integer.parseInt(JTemelet.getText()), Integer.parseInt(JTajto.getText()),
                    Integer.parseInt(JTnegyzetmeter.getText()), Integer.parseInt(Haz_ID.getText()));
            JTnev.setText("");
            JTemelet.setText("");
            JTajto.setText("");
            JTnegyzetmeter.setText("");
            JTID.setText("");
        }

        Show_UsersList_In_JTable();
    }//GEN-LAST:event_JBhozzaActionPerformed

    private void lakok_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lakok_tableMouseClicked
        int i = lakok_table.getSelectedRow();
        TableModel model = lakok_table.getModel();
        JTID.setText(model.getValueAt(i, 0).toString());
        JTnev.setText(model.getValueAt(i, 1).toString());
        JTemelet.setText(model.getValueAt(i, 2).toString());
        JTajto.setText(model.getValueAt(i, 3).toString());
        JTnegyzetmeter.setText(model.getValueAt(i, 4).toString());

    }//GEN-LAST:event_lakok_tableMouseClicked

    private void JBLaktorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLaktorolActionPerformed
        if (JTnev.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "KéremVálaszon Nevet", "Üres Mező", JOptionPane.INFORMATION_MESSAGE);

        } else {
            dbConnection.lakotorles(JTnev.getText());
            JTnev.setText("");
            JTemelet.setText("");
            JTajto.setText("");
            JTnegyzetmeter.setText("");
            JTID.setText("");
        }
        Show_UsersList_In_JTable();
    }//GEN-LAST:event_JBLaktorolActionPerformed

    private void JBModositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModositActionPerformed
        if (JTnev.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "KéremVálaszon Nevet", "Üres Mező", JOptionPane.INFORMATION_MESSAGE);

        } else {
            dbConnection.lakomodosit(JTnev.getText(), JTemelet.getText(), JTajto.getText(), JTID.getText());
            JTnev.setText("");
            JTemelet.setText("");
            JTajto.setText("");
            JTnegyzetmeter.setText("");
            JTID.setText("");
        }
        Show_UsersList_In_JTable();
    }//GEN-LAST:event_JBModositActionPerformed

    private void Lakok_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lakok_comboActionPerformed
        String nev = Lakok_combo.getSelectedItem().toString();
        Haz_ID.setText(nev.substring(nev.lastIndexOf(" ") + 1, nev.length()));
    }//GEN-LAST:event_Lakok_comboActionPerformed

    private void JBModosit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModosit1ActionPerformed
        Haz_ID.setText("");
        JTID.setText("");
        JTnev.setText("");
        JTemelet.setText("");
        JTajto.setText("");
        JTnegyzetmeter.setText("");
    }//GEN-LAST:event_JBModosit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kozoskepviselo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kozoskepviselo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kozoskepviselo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kozoskepviselo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                kozoskepviselo dialog = new kozoskepviselo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Haz_ID;
    private javax.swing.JButton JBLaktorol;
    private javax.swing.JButton JBModosit;
    private javax.swing.JButton JBModosit1;
    private javax.swing.JButton JBhozza;
    private javax.swing.JTextField JTID;
    private javax.swing.JTextField JTajto;
    private javax.swing.JTextField JTemelet;
    private javax.swing.JTextField JTnegyzetmeter;
    private javax.swing.JTextField JTnev;
    public static javax.swing.JComboBox<String> Lakok_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable lakok_table;
    // End of variables declaration//GEN-END:variables
}
